Projectweb/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from Project.views import *
admin.autodiscover()




urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^login/$', login_user, name='login'),
    url(r'^$', list_auctions, name='home'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^register/$', register_user, name='register'),
    url(r'^add_auction/$', add_auction.as_view(), name="add_bid"),
    url(r'^savebid/$', save_auction),
    url(r'^edit_auction/(\d+)/$', edit_auction),
    url(r'^search/$', search),
    url(r'^edit_auction_details/(\d+)/$', edit_auction_details),
    url(r'^makebid/$',bid),
    url(r'^ban_auction/(\d+)/$', bann_auction),
    url(r'^edit_profile/(\d+)/$', changelanguage,name='editprofile'),
    url(r'^editP/$', editP,name='editprofile'),
    url(r'^edit_language/$', editL,name='editL'),
    url(r'^showDetails/(\d+)/$', show_auction_details, name='showDetails'),
    url(r'^randomize/$', create_n_users),
    url(r'^auctionapi/$', create_auction_api),
    url(r'^bidapi/$', bid_api),
]

Project/forms.py
from time import timezone

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.urls import reverse
from datetime import datetime
from  Project.models import Auction
from Projectweb import settings


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )


class CreateBid(forms.Form):
    title = forms.CharField(max_length=200)
    details = forms.CharField(widget=forms.Textarea(), required=False)
    bid = forms.DecimalField(max_digits=10,decimal_places=2)
    bid_res = forms.CharField()


class confBid(forms.Form):
    CHOICES = [(x, x) for x in ("Yes", "No")]
    option = forms.ChoiceField(choices=CHOICES)

templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Simple Sidebar - Start Bootstrap Template</title>
    {% load static %}
    <!-- Bootstrap Core CSS -->
    <link href={% static "css/bootstrap.min.css" %} rel="stylesheet">
    <!-- Custom CSS -->
    <link href={% static "css/simple-sidebar.css" %} rel="stylesheet">
    <style>
        .bar1,
        .bar2,
        .bar3 {
            width: 35px;
            height: 5px;
            background-color: #333;
            margin: 6px 0;
            transition: 0.4s;
        }
    </style>
</head>

<body>
<div id="wrapper">
    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li class="sidebar-brand">
                Yet another ebay clone!

            </li>

            <li><a href="/">Home</a></li>
            <!--                <li><a href="#">Search bids</a></li>-->
            <li><a href="#search" data-toggle="collapse">{% trans "Search Auction" %}</a>
                <div id="search" class="collapse ">
                    <form class="form-search" action="/search/" method="get">
                        <input type="text" class="form-control" name="id" placeholder={% trans "Search for Auction" %}required=""
                               autofocus=""/>
                        <button class="btn btn-lg btn-primary btn-block " type="submit">{% trans "Search" %}</button>
                    </form>
                </div>
            </li>
            {% if user.is_authenticated %}
                    <li><a href="/add_auction/">{% trans "Create Auction" %}</a></li>
            {% endif %}


            <li>
                <a href="#api" data-toggle="collapse">API</a>
            </li>
                <div id="api" class="collapse ">
                    <label>Open in new tab to run example, if problem modify the URL</label>
                <a href="https://1988domi.pythonanywhere.com/auctionapi/?option=Yes&b_title=andi&b_details&b_bid=1&b_res=2018-12-30T09:09" data-toggle="collapse">Create a AUCTION API example </a>
                            <label></label>
                <a href="https://1988domi.pythonanywhere.com/bidapi/?aid=1&bid=1000000" data-toggle="collapse">Create a BID API example</a>
                </div>
            <li>
                <a href="#about" data-toggle="collapse">{% trans "About / Documentation" %}</a>
            </li>
                <div id="about" class="collapse ">
                            <label>Made with love and coffee </label>
                            <label>by Andi Domi!</label>
                    <a href="https://1988domi.pythonanywhere.com/randomize/?id=50" data-toggle="collapse">Create 50 users and 50 auctions</a>
                </div>
            </br>
            <div>
                <div class="">
             {% block navigation %}

                {% endblock %}
           {% if messages %}
        <ul class="messages col-lg-12 text-center">
            {% for message in messages %}
            <div{% if message.tags %} class="alert alert-info {{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endfor %}
        </ul>
    {% endif %}
                <form class="form-editPass" action="/edit_language/" method="POST">
                    {%  csrf_token %}
                    <select name="dropdown">
                    <option value='en'>English</option>
                    <option value='al'>Albanian</option>

                    </select><br>
                    <button class="btn btn-sm btn-primary "  type="submit">Select Language</button>
                </form>

        </ul>
    </div>
    <!--        content page-->
    <div id="page-content-wrapper">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">
                        <div class="container2" onclick="myFunction(this)">
                            <div class="bar1"></div>
                            <div class="bar2"></div>
                            <div class="bar3"></div>
                        </div>
                    </a>
                </div>

                <div class="footer_message alert alert-success text-center col-lg-11 hidden"></div>
            </div>
        </nav>
        <div class="container-fluid">
            <div class="row main">
                <div class="col-lg-12">
                    {% block content %}
                    {% endblock %}

                </div>
            </div>
        </div>
    </div>
</div>
<!-- /#page-content-wrapper -->
<!--    </div>-->
<script src={% static "js/jquery.js" %}></script>
<script src={% static "js/bootstrap.min.js" %}></script>
<script src={% static "js/tog_butt.js" %}></script>


<script>
    $("#menu-toggle").click(function (e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });


</script>

</body>
</html>

templates/bidlist.html
{% extends 'index.html' %}
{% load i18n %}
{% block content %}
{% load custom_Tag %}
    {% for auction in auction %}

        <h4> {{ auction.title }} </h4>
        {% ifequal auction.active 0 %}
            {% if request.user.is_superuser %}
                <a href="/ban_auction/{{ auction.id }}/">{% trans "Click here to Ban Auction!" %}</a>
            {% endif %}
            <p>{% trans "Auction created by" %}: <b> {{ auction.author }} </b></p>
            <p>{% trans "Auction created on" %}: <b> {{ auction.timestamp }}</b></p>
            <p>{% trans "Auction ended at" %}: <b>{{ auction.bid_res }}</b></p>
            <p>{% trans "Details" %}: <b>{{ auction.details }}</b></p>
            {% trans "Auction resolved! The winner is" %}: {{ auction.last_bider }}: <b>{{ auction.last_bid }}</b>
            <br>
            <br>
            <br>

        {% else %}
            {% ifequal auction.author|slugify  authuser|slugify %}
                {% ifequal auction.active 1 %}
                <a href="/edit_auction/{{ auction.id }}/">{% trans "Edit Details" %}</a>
                {% endifequal%}
            {% endifequal %}

            {% if request.user.is_superuser and auction.banned == 0  %}
                <a href="/ban_auction/{{ auction.id }}/">{% trans "Click here to Ban Auction!" %}</a>
            {% endif %}
            {%  if auction.banned == 1 %}
                <label> Auction Banned! No modification can be done to this auction!</label>
            {% endif %}
            <p>{% trans "Auction created by" %}: <b> {{ auction.author }} </b></p>
            <p>{% trans "Auction created on" %}: <b> {{ auction.timestamp }}</b></p>
            <p>{% trans "Auction ends at" %}: <b>{{ auction.bid_res }}</b></p>
            <p>{% trans "Details" %}: <b>{{ auction.details }}</b></p>
            {% trans "Current bid made by" %} {{ auction.last_bider }}: {{ auction.last_bid }} {{ "€" }}
            <p>
            {% trans "Current bid converted to the latest exchange rate" %}: {{ auction.last_bid|multiply:dollar }} {{ "$" }}
            <p>
                {% if guest %}
                    {{ guest }}
                    </p>

                {% endif %}
            {% if not guest %}

                {% if auction.author != authuser and auction.last_bider != authuser and auction.banned == 0 %}

                    {%  if auction.last_bider == authuser %}
                        <label>The logged in user is the one who did the last bid</label>
                    {% endif %}

                    <form action="/makebid/" method="post">
                        {% csrf_token %}
                        <input type="number" step="0.01" name="bid" min="{{ auction.last_bid }}" required="" id="bid"
                               placeholder={{ auction.last_bid }}>
                        <input type="hidden" name="version" value="{{ auction.version }}">
                        <input type="submit" value="Bid">
                        <input type="hidden" name="auction_ID" value="{{auction.id}}">
                    </form>
                {% else %}
                    {% if auction.author|slugify == authuser|slugify and auction.last_bider|slugify == authuser|slugify %}
                <label>You cannot bid on your own auction !</label>
                    {% elif auction.author|slugify != authuser|slugify and auction.last_bider|slugify == authuser|slugify %}
                        <label><i><h6>You cannot make an offer in your own bid !</h6></i></label>
                    {% endif %}
                    {% endif %}




            {% endif %}

            </p>
            <br>
            <br>
            <br>
        {% endifequal %}
    {% empty %}
        <p>{% trans "No bids" %}<p>

    {% endfor %}

{% endblock %}

templates/changepass.html
{% extends "base.html" %}
{% load i18n %}
{% block navigation %}
                        <ul class="nav nav-tabs" id="sync-tabs">
                            <li class="active text-center "><a class="text-center" data-toggle="tab" href="#home">{% trans "Login" %}</a> </li>
                            <li class=""><a href="/register">{% trans "Register" %}</a></li>
                        </ul>
                    </div>
                    <div class="tab-content ">
                        <div id="home" class="tab-pane fade in active col-lg-12 ">
                            <div class="wrapper ">

                                <form class="form-signin " method="post">
                                    <!--<h2 class="form-signin-heading">Login</h2>-->
                                    {% csrf_token %}
                                    <div class="loginclass">
                                    {% for field in form %}

                                    <div class="fieldWrapper">
                                        {{ field.errors }}
                                        {{ field.label_tag }}: {{ field }}
                                    </div>
                                        </div>
                                    {% endfor %}

                                    <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans "Login" %}</button>
                                </form>
                            </div>
                        </div>

                    </div>

            {% endblock %}

templates/createbid.html
{% extends "index.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}

  {% if error%}
  <p> <b>{{ error }}</b> </p>
    {% endif %}
<form action="/add_auction/" method="post">
    {% csrf_token %}
    <p><label for="id_title">Title of the auction :</label> <input type="text" name="title" maxlength="200" required="" id="id_title"></p>
<p><label for="id_details">The description of the auction :</label> <textarea name="details" cols="40" rows="10" id="id_details"></textarea></p>
<p><label for="id_bid">Starting bid (€) :</label> <input type="number" name="bid" step="0.01" required="" id="id_bid"></p>
<p><label for="id_bid_res">Time for the bid to be active (minimum is set to 72h):</label> <input type="datetime-local" name="bid_res" required="" id="id_bid_res" min={{ time }} value={{ time }}></p>
    <input type="submit" value="Submit">
</form>


{% endblock %}

templates/editbid.html
{% extends 'index.html' %}
{% load i18n %}
{% block title %}{% trans "Edit your bid" %} {% endblock %}

{% block content %}

<p><b>{% trans "Edit Bid:" %}. {{ title }}</b></p>
    <form action="/edit_auction_details/{{ id }}/" method="post">
        {%  csrf_token %}
       <p>{% trans " Details:"%}  <textarea name="details" cols="50" rows="20">{{ bid_details }}</textarea></p>
        <input type="number" name="version" hidden value="{{ version }}">
        <input type="submit" value="Change">
    </form>

{% endblock %}

templates/editprofile.html
{% extends "base.html" %}
{% load i18n %}
{% block navigation %}
    {% if request.user.is_authenticated %}

        <ul class="nav nav-tabs" id="sync-tabs">
            <li class="hi"><a href="/">{% trans "Profile" %}</a></li>
            <li class="clear hi active"><a data-toggle="tab" href="#menu3">{% trans "Edit Profile" %}</a></li>
        </ul>
        </div>
        <div id="menu3" class="tab-pane fade fade in active ">
            <div id="menu3" class="tab-pane fade col-lg-12 active in">

                <form class="form-editPass" action="/edit_profile/{{ request.user.id }}" method="get">
                    {%  csrf_token %}

                    <h4>Edit your email and/or password</h4>
                    <input type="email" class="form-control" name="email" placeholder="Email">
                    <input type="password" class="form-control" name="password" placeholder="Type Password Again">
                    <button class="btn btn-lg btn-primary btn-block" type="submit">Edit profile</button>
                </form>
            </div>
        </div>
        </div>



    {% else %}

        <ul class="nav nav-tabs" id="sync-tabs">
            <li class="active text-center "><a class="text-center" href="/login/">{% trans "Login" %}</a></li>
            <li class=""><a href="/register/">{% trans "Register" %}</a></li>
        </ul>

        <h4>{% trans "Welcome Guest, please click the above button to login or register" %}</h4>

        </div>

    {% endif %}
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% block navigation %}
                    {% if request.user.is_authenticated %}

                        <ul class="nav nav-tabs" id="sync-tabs">
                            <li class="clear hi active"><a data-toggle="tab" href="#menu2">{% trans "Profile" %}</a></li>
                            <li class="hi"><a  href="/editP">{% trans "Edit Profile" %}</a></li>
                        </ul>
                        </div>
                        <div id="menu2" class="tab-pane fade fade in active ">
                            <div class="col-lg-12 text-center">
                                <h4>{% trans "Welcome" %} {{request.user.username}}</h4>
                            </div>

                                <div class="row">
                                    <div class="col-lg-12 text-center">
                                        <a>
                                            <h4><a href="/logout"/> {% trans "Logout" %} </h4>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% else %}

                        <ul class="nav nav-tabs" id="sync-tabs">
                            <li class="active text-center "><a class="text-center" href="/login/">{% trans "Login" %}</a></li>
                            <li class=""><a href="/register/">{% trans "Register" %}</a></li>
                        </ul>

                        <h4>{% trans "Welcome Guest, please click the above button to login or register" %}</h4>

                        </div>

                    {% endif %}
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load i18n %}
{% block navigation %}
                        <ul class="nav nav-tabs" id="sync-tabs">
                            <li class="active text-center "><a class="text-center" data-toggle="tab" href="#home">{% trans "Login" %}</a> </li>
                            <li class=""><a href="/register">{% trans "Register" %}</a></li>
                        </ul>
                    </div>
                    <div class="tab-content ">
                        <div id="home" class="tab-pane fade in active col-lg-12 ">
                            <div class="wrapper ">

                                <form class="form-signin" method="post" >
                                    <!--<h2 class="form-signin-heading">Login</h2>-->
                                    {% csrf_token %}
                                    <!--<h2 class="form-signin-heading">Login</h2>-->
                                    <div class="loginclass">
                                    <div class="fieldWrapper">
                                        <label for="id_username">Username:</label>: <input type="text" name="username" autofocus="" maxlength="254" required="" id="username">
                                    </div>
                                        </div>

                                    <div class="fieldWrapper">
                                        <label for="id_password">Password:</label>: <input type="password" name="password" required="" id="password">
                                    </div>
                                        <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans "Login" %}</button>
                                </form>
                            </div>
                        </div>

                    </div>

            {% endblock %}

templates/logout.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Simple Sidebar - Start Bootstrap Template</title>
    {% load static %}
    <!-- Bootstrap Core CSS -->
    <link href={% static "css/bootstrap.min.css"%} rel="stylesheet">
    <!-- Custom CSS -->
    <link href={% static "css/simple-sidebar.css"%} rel="stylesheet">
<style>
        .bar1,
        .bar2,
        .bar3 {
            width: 35px;
            height: 5px;
            background-color: #333;
            margin: 6px 0;
            transition: 0.4s;
        }
    </style>
</head>

<body>
    <div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand"> Yet another ebay clone!</li>
                <li><a href="#">{% trans "Home" %}</a></li>
                <!--                <li><a href="#">Search bids</a></li>-->
                <li><a href="#search" data-toggle="collapse">{% trans "Search Auction" %}</a>
                    <div id="search" class="collapse ">
                        <form class="form-search">
                            <input type="text" class="form-control" name="search" placeholder="{% trans "Search for Auction" %}" required="" autofocus="" />
                            <button class="btn btn-lg btn-primary btn-block " type="submit">{% trans "Search" %}</button>
                        </form>
                    </div>
                </li>
                <li><a href="#">{% trans "Auctions" %}</a></li>
                <li><a href="#">{% trans "Create Auction" %}</a></li>
                <li><a href="#">API</a></li>
                <li><a href="#">{% trans "About / Documentation" %}</a></li>
                </br>
                <div>
                    <div class="">
                        <ul class="nav nav-tabs" id="sync-tabs">
                            <li class="active text-center "><a class="text-center" data-toggle="tab" href="#home">{% trans "Login" %}</a> </li>
                            <li class=""><a data-toggle="tab" href="#menu1">{% trans "Register" %}</a></li>
                        </ul>
                    </div>
                    <div class="tab-content ">
                        <div id="home" class="tab-pane fade in active col-lg-12 ">
                            <div class="wrapper ">
                                <form class="form-signin " method="post">
                                    <!--<h2 class="form-signin-heading">Login</h2>-->
                                    {% csrf_token %}
                                    <div class="loginclass">
                                    {{ form.as_ul }}
                                    </div>
                                    <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans "Login" %}</button>
                                </form>
                            </div>
                        </div>
                        <div id="menu1" class="tab-pane fade col-lg-12 ">
                            <div class="">
                                <form class="form-signin">
                                    <!--<h2 class="form-signin-heading">Register</h2>-->
                                    <input type="text" class="form-control" name="username" placeholder="{% trans "Email Address" %}" required="" autofocus="" />
                                    <input type="password" class="form-control" name="password" placeholder="{% trans "Password" %}" required="" />
                                    <input type="password" class="form-control" name="password" placeholder="{% trans "Type Password Again" %}" required="" />
                                    <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans "Register" %}</button>
                                </form>
                            </div>
                        </div>

                    </div>
            </ul>
            </div>
            <!--        content page-->
            <div id="page-content-wrapper">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">
                                <div class="container2" onclick="myFunction(this)">
                                    <div class="bar1"></div>
                                    <div class="bar2"></div>
                                    <div class="bar3"></div>
                                </div>
                            </a>
                        </div>
                        <div class="footer_message alert alert-success text-center col-lg-11 hidden">hello</div>
                    </div>
                </nav>
                <div class="container-fluid">
                    <div class="row main">
                        <div class="col-lg-12"> </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->
        <!--    </div>-->
        <script src={% static "js/jquery.js"%}></script>
        <script src={% static "js/bootstrap.min.js"%}></script>
        <script src={% static "js/tog_butt.js"%}></script>
        <script>
            $("#menu-toggle").click(function (e) {
                e.preventDefault();
                $("#wrapper").toggleClass("toggled");
            });
        </script>
</body>

</html>

templates/register.html
{% extends "base.html" %}
{% load i18n %}
{% block navigation %}
                    <ul class="nav nav-tabs" id="sync-tabs">
                        <li class="active text-center "><a href="/login">{% trans "Login" %}</a>
                        </li>
                        <li class=""><a data-toggle="tab" href="#menu1">{% trans "Register" %}</a></li>
                    </ul>
                </div>
                <div class="tab-content ">
                    <div id="menu1" class="tab-pane fade col-lg-10 fade in active ">
                        <div class="">

                            <form action="" class="form-signin" method="post">
                            {% csrf_token %}
                                    {% for field in form %}

                                    <div class="fieldWrapper">
                                        {{ field.errors }}
                                        {{ field.label_tag }}: {{ field }}
                                    </div>
                          {% endfor %}
                                <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans "Register" %}</button>

                            </form>

                        </div>
                    </div>

                </div>

{% endblock %}

templates/wizardtest.html
{% extends "base.html" %}
{% load i18n %}

<h2> {% trans "Add Auction" %}</h2>
{% block content %}

<p><b>{% trans "Confirm the creation of an Auction" %}</b></p>
{% if error %}
  {{ error}}
{% endif %}

<p>{{b_title}}</p>
<p>{{b_details}}</p>
<p>{{b_bid}}</p>
<p>{{b_res}}</p>

    <form action="/savebid/" method="post">
        {% csrf_token %}
         {{ form.as_p }}
         <INPUT TYPE=HIDDEN NAME="b_title" VALUE={{b_title}}>
		 <INPUT TYPE=HIDDEN NAME="b_details" VALUE={{b_details}}>
         <INPUT TYPE=HIDDEN NAME="b_bid" VALUE={{b_bid}}>
		 <INPUT TYPE=HIDDEN NAME="b_res" VALUE={{b_res}}>
        <input type="submit" value="Submit">
    </form>


{% endblock %}